version: '3.8'

services:
  proxy:
    container_name: proxy
    image: ghcr.io/vo1odko/blackblaze/proxy
    build:
      context: proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:80"
    depends_on:
      - core
      - cdn
    networks:
      - app

  core:
    container_name: core
    image: ghcr.io/vo1odko/blackblaze/core
    build:
      context: core
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    expose:
      - "8080"
    networks:
      - app

  cdn:
    container_name: cdn
    image: ghcr.io/vo1odko/blackblaze/cdn
    build:
      context: cdn
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/usr/local/apache2/htdocs/
    expose:
      - "8080"
    networks:
      - app

  psql:
    container_name: psql
    image: ghcr.io/vo1odko/blackblaze/psql
    build:
      context: psql
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${DB_USR}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app:
    name: app
    driver: bridge
